services:

  pen_drive_python:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    container_name: pen_drive_python
    image: pen_drive_python
    networks:
      - pen_drive
    volumes:
      - ./src:/pen-drive

networks:
  pen_drive:
    name: pen_drive
    driver: bridge
